### ISSUE TITLE
英文的两端对齐，会导致每个字母间距变大 。似乎应该根据单词来

### ISSUE THREAD

**Issue by Passer-by** [mabDc/text_composition#8]

**Comment by Passer-by** [comment]
不知为何，我在canvas中使用textpianter 设置 textAlign: TextAlign.justify并没有起到效果

**Comment by a1017480401** [comment]
![image](https://user-images.githubusercontent.com/58846244/157211929-429d512d-21e4-4a8d-8f38-2d05ca3f9635.png)

我现在做了点特殊处理，来保证英文的排版是按照单词分割

**Comment by Passer-by** [comment]
不知道你这边有没有更好的方案

**Comment by mabDc** [comment]
我没有比较好的方案，这个东西其实是针对中文的，英文文本用textAlign: justify应该就足够，中文应该是flutter的bug，但是我这个却是根据字符重新计算间距，所以不适合单词

**Comment by Passer-by** [comment]
很难过

**Comment by mabDc** [comment]
> 不知为何，我在canvas中使用textpianter 设置 textAlign: TextAlign.justify并没有起到效果

如果想用这个属性，就应该去掉letterspacing的设置，两者可能冲突

**Comment by Passer-by** [comment]
我除去了。但还是不行

**Comment by mabDc** [comment]
canvas是自己绘制字符，最大的问题在于标点符号，分行

**Comment by mabDc** [comment]
> 我除去了。但还是不行

是纯英文还是中英文混合？纯英文没必要使用这么麻烦的手段，如果是混合，那应该属于flutter的bug，它对中文处理有毛病

**Comment by Passer-by** [comment]
> canvas是自己绘制字符，最大的问题在于标点符号，分行

混合。已经快自闭了

**Comment by mabDc** [comment]
不知道flutter里的源码怎么计算的，修复它的源码才是正道，我这个canvas也是曲线救国

**Comment by Passer-by** [comment]
这个问题iusse都提了2年多了。flutter团队还是不修复

**Comment by mabDc** [comment]
flutter源码里justify我测试是间距小于一个汉字时自动调节正常，大于一个汉字才有问题，就像word里的两端对齐加上左对齐的混合版，当剩余空间太大时它没有自动调节间距

**Comment by mabDc** [comment]
> flutter源码里justify我测试是间距小于一个汉字时自动调节正常，大于一个汉字才有问题，就像word里的两端对齐加上左对齐的混合版，当剩余空间太大时它没有自动调节间距

因为中文的换行有时候是最后一个字紧接着句号引号，可能是40px的宽度，如果当前行剩余38px的宽度，就会容纳不下，这时候显示就出现问题，而如果当前行最后一个刚好容纳不下字后面没有符号，那这个宽度可能是十几px，这时候它内部的自动调节似乎正常工作

**Comment by mabDc** [comment]
> 这个问题iusse都提了2年多了。flutter团队还是不修复

这个可能正常，以前不理解，后来有点理解了。如果我是开发者，而你提的问题我自己如果完全遇不上，就不会想着修复，除非我也遇到了或者你自己提供了修复的方案，我才会想着尝试

**Comment by mabDc** [comment]
flutter源码里justfy我测试是间距小于一个汉字时自动调节正常，大于一个汉字才有问题，就像word里的两端对齐加上左对齐的混合版，当剩余空间太大时它没有自动调节间距

**Comment by mabDc** [comment]
感觉还是要自己硬着头皮看源码才行，不过给谷歌pr还是挺麻烦，有一些验证，没了解过

**Comment by mabDc** [comment]
我猜想谷歌也是绘制两次重新调节再显示的，它的引擎也要多次计算

**Comment by Passer-by** [comment]
不太清楚。但是flutter canvas画文字的消耗似乎还挺大的 。你这边有做过耗电测试吗

**Comment by mabDc** [comment]
消耗应该不大。如果加上截图和动画才会有消耗，我用这个canvas实时绘制加动画还是很流畅，可以保持60fps

**Comment by mabDc** [comment]
单纯计算间距，100页屏幕的文本耗时会是几百毫秒，然后显示其实可以控制只画一屏幕

**Comment by mabDc** [comment]
> 不知道你这边有没有更好的方案

你的方案就把所有地方间距全都放进wordspacing里，感觉排班也不好看…只是勉强能用

**Comment by Passer-by** [comment]
> > 不知道你这边有没有更好的方案
> 
> 你的方案就把所有地方间距全都放进wordspacing里，感觉排班也不好看…只是勉强能用

我现在是放弃了中英文混合 ，如果是纯英文就去掉首尾的空格 ， 然后再根据单行有多个空格然后再去计算wordspacing

**Comment by Passer-by** [comment]
能用。但应该有隐患

**Comment by mabDc** [comment]
> 不太清楚。但是flutter canvas画文字的消耗似乎还挺大的 。你这边有做过耗电测试吗

耗电的话，我自己使用，看小说一小时耗电量比其他阅读器小。但是要看你app内部其他任务，你后台可能要发送统计信息，要保存记录，有网络请求，也有存储读写操作

**Comment by mabDc** [comment]
比如绘制电量和时间并且实时刷新我也觉得消耗不小…我发现比如起点，它时间和电量是不刷新的，只有翻到下一页重新画了才更新

**Comment by Passer-by** [comment]
> 

我目前是会刷新的，但我不是在canvas里面。我尽量保证canvas能不动就不动

**Comment by mabDc** [comment]
这个bug似乎安卓本身存在，你也可以看看其他安卓项目，也有用画笔画排班的，也许有更好方案。前几天有人跟我说他以前kotlin写的app，也是canvas，改到用dart工作量不大，自己写的排班也工作正常，不过它的app是准备盈利的，我也不甚了解

**Comment by Passer-by** [comment]
> 

你说的是他吗 [lwlizhe](https://github.com/lwlizhe)

**Comment by mabDc** [comment]
> > 
> 
> 你说的是他吗 [lwlizhe](https://github.com/lwlizhe)

这个人不错，但是他写的太早了，他的追书神器排版计算实在太久了，体验就有点糟糕，动画不错，不过我觉得还是可以改进，可能他也是时间不够

**Comment by mabDc** [comment]
canvas画的其实可以不截屏直接用矩阵变换

**Comment by mabDc** [comment]
你知道的，除了大学生期间能有大把时间做想做的，可以follow your heart，其他时候忙着做的东西不一定是真的想做的，
